# Generated by Django 3.2.5 on 2021-07-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Profile_Pic', models.ImageField(upload_to='')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=12)),
                ('Company_Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
